force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Booking_Channel__c.field-meta.xml
<CustomField>
    <fullName>Booking_Channel__c</fullName>
    <label>Appointment Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/PatientEmail__c.field-meta.xml
<CustomField>
    <fullName>PatientEmail__c</fullName>
    <formula>Patient__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Patient Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Physician__c.field-meta.xml
<CustomField>
    <fullName>Physician__c</fullName>
    <label>Physician</label>
    <referenceTo>Physician__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Physician_Email__c.field-meta.xml
<CustomField>
    <fullName>Physician_Email__c</fullName>
    <label>Physician Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/PhysicianEmail__c.field-meta.xml
<CustomField>
    <fullName>PhysicianEmail__c</fullName>
    <formula>Physician__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Physician Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/StartTiming__c.field-meta.xml
<CustomField>
    <fullName>StartTiming__c</fullName>
    <label>Start Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Physician__c/Physician__c.object-meta.xml
<CustomObject>
    <label>Physician</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AppointmentTriggerHandler.cls
public class AppointmentTriggerHandler {
    public  void beforeInsert(List<Appointment__c> newAppointmentList){
        for(Appointment__c appointment:newAppointmentList){
            Time myTime = Time.newInstance(integer.valueof(appointment.StartTiming__c.substring(0,2)),Integer.valueof(appointment.StartTiming__c.substring(3,5)),00,00);
            appointment.StartTime__c=myTime;
            Datetime dt = Datetime.newInstance(appointment.Start_Time__c,appointment.StartTime__c);
            appointment.End_Time__c=dt.addMinutes(15);
            appointment.Start_Date_Time__c=dt;
            appointment.Physician_Email__c=appointment.PhysicianEmail__c;
            appointment.Patient_Email__c=appointment.PatientEmail__c;
            system.debug(appointment.Patient__c);
        }  
    }
    public void afterInsert(List<Appointment__c> newAppointmentList){
        set<Id> apppointmentData=new  set<Id>();
        List<Event> listOfEvent=new List<Event>();
        for(Appointment__c appointment:newAppointmentList){
            Event event=new Event();
            event.Physician__c=appointment.Physician__c;
            event.WhatId=appointment.Patient__c;
            event.Subject=appointment.Booking_Channel__c;
            event.StartDateTime=appointment.Start_Date_Time__c;
            event.EndDateTime=appointment.End_Time__c;
            event.Appointment__c=appointment.Id;
            listOfEvent.add(event);
            apppointmentData.add(appointment.Id);
        }  
        if(!listOfEvent.isEmpty()){
            insert listOfEvent;   
        }
        if(!apppointmentData.isEmpty()){
            GoogleWebService.doCreateNewEvent(apppointmentData);   
        }
    }
    public  void afterDelete(List<Appointment__c> oldAppointmentList){
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        for(Appointment__c opp: oldAppointmentList)
        {
            if(opp.PatientEmail__c!=null){
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                email.setToAddresses(new String[] {opp.PatientEmail__c});
                email.setSubject('Appointment Cancelled Notification');
                email.setPlainTextBody('As per your unavailability for ' + opp.Booking_Channel__c + ' on'+opp.StartTime__c+' '+opp.StartTiming__c+'has been cancelled.');
                emails.add(email);      
            }
            
        }
        if(!emails.isEmpty()){
            Messaging.sendEmail(emails);
        }
        
    }
    
}