force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Booking_Channel__c.field-meta.xml
<CustomField>
    <fullName>Booking_Channel__c</fullName>
    <label>Appointment Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/CalendarId__c.field-meta.xml
<CustomField>
    <fullName>CalendarId__c</fullName>
    <label>CalendarId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/GoogleEventId__c.field-meta.xml
<CustomField>
    <fullName>GoogleEventId__c</fullName>
    <label>GoogleEventId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/PatientEmail__c.field-meta.xml
<CustomField>
    <fullName>PatientEmail__c</fullName>
    <formula>Patient__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Patient Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Physician__c.field-meta.xml
<CustomField>
    <fullName>Physician__c</fullName>
    <label>Physician</label>
    <referenceTo>Physician__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/PhysicianEmail__c.field-meta.xml
<CustomField>
    <fullName>PhysicianEmail__c</fullName>
    <formula>Physician__r.Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Physician Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Physician__c/Physician__c.object-meta.xml
<CustomObject>
    <label>Physician</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GoogleWebService.cls
public with sharing class GoogleWebService {
    /*Class to get calendar details
     * create calendar
     * create event
     * delete event*/
    public static Http http = new Http();
    public static HTTPResponse response;
    public static HttpRequest request;
    public static void getMyCalendar() {
        
        request = new HttpRequest();
        request.setMethod('GET');
        request.setEndpoint('callout:Google_Connect/calendar/v3/users/me/calendarList');
        
        response = http.send(request); 
        
        System.debug(response.getBody());
    }
    public static void CreateCalender(String Summary) {
        String requestBody = '{'+
            '"summary":'+'"'+ Summary+'"'+
            '}';
        System.debug('#### requestBody '+requestBody);
        
        request = new HttpRequest();
        request.setMethod('POST');
        request.setEndpoint('callout:Google_Connect/calendar/v3/calendars');
        request.setBody(requestBody);        
        response = http.send(request); 
        
        System.debug(response.getBody());
    }
    @future(callout=true)
    public static void doCreateNewEvent(set<Id> appointmentId) {
        String calendarId=System.Label.CalendarId;
        
        List<Appointment__c> appointList=[Select Id,PhysicianEmail__c,PatientEmail__c,Booking_Channel__c,Start_Date_Time__c,StartTime__c,Start_Time__c,Physician__c,End_Time__c from Appointment__c where Id IN:appointmentId ];
        for(Appointment__c app:appointList){
            String requestBody1 = '{'+
                '"end":'+'{'+
                '"dateTime":'+'"'+app.End_Time__c.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')+'"'+','+
                '"timeZone":'+'"'+UserInfo.getTimeZone()+'"'+
                '},'+
                '"start": '+'{'+
                '"dateTime":'+'"'+app.Start_Date_Time__c.formatGmt('yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z\'')+'"'+','+
                '"timeZone":'+ '"'+UserInfo.getTimeZone()+'"'+
                '}'+','+
                '"summary":'+'"'+ app.Booking_Channel__c+'"'+','+
                '"attendees":'+'['+
                '{'+'"email":'+ '"'+app.PhysicianEmail__c+'"'+'}'+','+
                '{'+'"email":'+ '"'+app.PatientEmail__c+'"'+'}'+
                ']'+
                '}';
            System.debug('#### requestBody1 '+requestBody1);
            
            request = new HttpRequest();
            request.setMethod('POST');
            request.setEndpoint('callout:Google_Connect/calendar/v3/calendars/gd8hiinn5lncjud972bpjncgj0@group.calendar.google.com/events');
            request.setBody(requestBody1);        
            response = http.send(request); 
        	Map<String, Object> mapOfString = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
          	app.GoogleEventId__c=(String)mapOfString.get('id');
          	app.CalendarId__c=calendarId;
            System.debug(response.getBody()); 
        }
        update appointList;
        
    }
     public static void deleteCalendarEvent(String calendarId,String eventId) {
            request = new HttpRequest();
            request.setMethod('DELETE');
            request.setEndpoint('callout:Google_Connect/calendar/v3/calendars/gd8hiinn5lncjud972bpjncgj0@group.calendar.google.com/events/'+eventId);
            response = http.send(request); 
            
            System.debug(response.getBody()); 
        }
        
    
}