force-app/main/default/objects/Appointment__c/Appointment__c.object-meta.xml
<CustomObject>
    <label>Appointment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Appointment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Appointment__c/fields/Clinic__c.field-meta.xml
<CustomField>
    <fullName>Clinic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinic</label>
    <referenceTo>Clinic__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Patient__c.field-meta.xml
<CustomField>
    <fullName>Patient__c</fullName>
    <label>Patient</label>
    <referenceTo>Patient__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Appointment__c/fields/Physician__c.field-meta.xml
<CustomField>
    <fullName>Physician__c</fullName>
    <label>Physician</label>
    <referenceTo>Physician__c</referenceTo>
    <relationshipLabel>Appointment</relationshipLabel>
    <relationshipName>Appointment</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clinic__c/Clinic__c.object-meta.xml
<CustomObject>
    <label>Clinic</label>
    <nameField>
        <label>Clinic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clinics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Physician__c/Physician__c.object-meta.xml
<CustomObject>
    <label>Physician</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Physician__c/fields/Clinic__c.field-meta.xml
<CustomField>
    <fullName>Clinic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinic</label>
    <referenceTo>Clinic__c</referenceTo>
    <relationshipLabel>Physicians</relationshipLabel>
    <relationshipName>Physicians</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Physician__c/fields/Practicing_From__c.field-meta.xml
<CustomField>
    <fullName>Practicing_From__c</fullName>
    <label>Practicing From</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Physician__c/fields/Specialization_Price__c.field-meta.xml
<CustomField>
    <fullName>Specialization_Price__c</fullName>
    <label>Specialization Price</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Specializations__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>800</fullName>
            </value>
            <value>
                <fullName>1000</fullName>
            </value>
            <value>
                <fullName>1200</fullName>
            </value>
            <value>
                <fullName>1500</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Physician__c/fields/Specializations__c.field-meta.xml
<CustomField>
    <fullName>Specializations__c</fullName>
    <label>Specializations</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cardiology</fullName>
            </value>
            <value>
                <fullName>Endocrinology</fullName>
            </value>
            <value>
                <fullName>Rheumatology</fullName>
            </value>
            <value>
                <fullName>General Practice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Physician_Timing__c/Physician_Timing__c.object-meta.xml
<CustomObject>
    <label>Physician Timing</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Physician Timing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Physicians Timings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Physician_Timing__c/fields/Physician__c.field-meta.xml
<CustomField>
    <fullName>Physician__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Physician</label>
    <referenceTo>Physician__c</referenceTo>
    <relationshipLabel>Physicians Timings</relationshipLabel>
    <relationshipName>Physicians_Timings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Physician_Timing__c/fields/Timings__c.field-meta.xml
<CustomField>
    <fullName>Timings__c</fullName>
    <label>Timings</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10:00 AM</fullName>
            </value>
            <value>
                <fullName>10:15 AM</fullName>
            </value>
            <value>
                <fullName>10:30 AM</fullName>
            </value>
            <value>
                <fullName>10:45 AM</fullName>
            </value>
            <value>
                <fullName>11:00 AM</fullName>
            </value>
            <value>
                <fullName>11:15 AM</fullName>
            </value>
            <value>
                <fullName>11:30 AM</fullName>
            </value>
            <value>
                <fullName>11:45 AM</fullName>
            </value>
            <value>
                <fullName>12:00 AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BookPatientAppointmentController.cls
public class BookPatientAppointmentController {
    @AuraEnabled 
    public static Appointment__c searchLatestPatientAppointment(String searchTerm){   
        return [Select Physician__r.Specialization_Price__c,Patient__r.Name,Patient__r.Last_Name__c,Patient__r.Email__c,Patient__r.Street__c,Patient__r.City__c,Patient__r.Picture__c,Patient__r.Contact_Number__c,Id from Appointment__c
                where Patient__r.Name=:searchTerm OR Patient__r.Last_Name__c =:searchTerm OR Patient__r.Contact_Number__c=:searchTerm order by createdDate Desc limit 1];

    }
  
    
    @AuraEnabled 
    public static Map<String, String> specializationFieldValue(){
        Map<String, String> options = new Map<String, String>();
        
        Schema.DescribeFieldResult fieldResult = Physician__c.Specializations__c.getDescribe();
        
        List<Schema.PicklistEntry> pValues = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: pValues) {
            
            options.put(p.getValue(), p.getLabel());
        }
        return options;
    }
    @AuraEnabled
    public static  List<Physician__c> physicianBySpec(String specialization ) {
        List<Physician__c> physician = new  List<Physician__c>();
        physician= [Select Name,Last_Name__c,Email__c,Clinic__c,Specializations__c,Practicing_From__c,Picture_URL__c,Specialization_Price__c,Id from Physician__c where Specializations__c=:specialization];
        return physician;
    }
    @AuraEnabled
    public static  Physician__c physicianData(String Id ) {
        return [Select Name,Last_Name__c,Clinic__c,Specializations__c,Practicing_From__c,Picture_URL__c,Specialization_Price__c,Id from Physician__c where Id=:Id];
    }
    @AuraEnabled
    public static  List<wrapSlot> selectPhysicianTime(String physicianId,String selectedDate) {
        system.debug(selectedDate);
        List<String> physiciantimings = new  List<String>();
        Physician_Timing__c p= [Select Id,Timings__c from Physician_Timing__c where Physician__c=:physicianId and Active__c=true order by createdDate Desc];
        physiciantimings.addAll(p.Timings__c.split(';'));
        Date todaysDate=Date.valueOf(selectedDate);
        system.debug('todaysDate----'+todaysDate);
        List<wrapSlot>  wrapSlotList= new List<wrapSlot>();
        List<wrapSlot>  wrapSlotList1= new List<wrapSlot>();
        set<String>  timedata= new  set<String>();
        for(Event a: [Select Id,StartDateTime,EndDateTime,Physician__c from Event where Physician__c=:physicianId ]) {
            system.debug('------'+a);
            Date startdate=Date.newInstance(a.StartDateTime.year(),a.StartDateTime.month(),a.StartDateTime.day());
            system.debug(startdate);
            if(startdate==todaysDate){
                String times=String.valueOf(a.StartDateTime.format('hh:mm a'));
                System.debug(times);
                if(physiciantimings.contains(times)){
                    wrapSlotList.add(new wrapSlot(times,true));
                    timedata.add(times);
                }  
            }
            
        }
        for(String timings:physiciantimings){
            if(!timedata.contains(timings)){
                wrapSlotList.add(new wrapSlot(timings,false));
            }
        }
        system.debug(wrapSlotList);
        return wrapSlotList;
    }
    public class wrapSlot {
        @AuraEnabled
        public String Timing {get; set;}
        @AuraEnabled
        public Boolean isBooked {get; set;}
        
        public wrapSlot(String t,boolean booking) {
            Timing = t;
            isBooked = booking;
        }
    }
    
}